services:
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - ./packages:/app/packages
      - /app/apps/frontend/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000/api      
      - CHOKIDAR_USEPOLLING=true
      - VITE_BETTER_AUTH_URL=${BETTER_AUTH_URL}
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: dev
    ports:
      - "5000:5000" 
      - "9229:9229"
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages:/app/packages
      - /app/apps/backend/node_modules
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - TRUSTED_FRONTEND=${TRUSTED_FRONTEND}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
